logging:
  output: stdout
triggers:
  - name: example
    run:
      timeout: 1h
      concurrency: 1
      exec: /bin/echo
      args:
        expression: "{{ .Attributes.foobar }} {{ .Payload.foo.bar }}"
    pubsub:
      project: sample-project-123
      subscription: execd-demo-sub

